
collision:
  margin: "0.006"
  solref: "0.0005 1"
  solimp: "0.998 0.9999 0.0005"

object_collision:
  margin: "0.007"
  solref: "0.004 1.0"
  solimp: "0.98 0.995 0.0001"

joint:
  freejoint_damping: "0.078"

simulation:
  timestep: "0.001"
  memory: "64M"
  solver_iterations: 100
  solver_ls_iterations: 35
  solver_noslip_iterations: 90

material:
  specular: "0.4"
  shininess: "0.001"

defaults:
  z_offset: 0.005
  inertia_scale: 0.002

contact_pair:
  condim: 4
  solref: "0.0006 1.5"
  solimp: "0.996 0.997 0.00001"
  friction: "200.0 10.0 10.0"
